"""Add status column to donasi

Revision ID: c9c5dbcd347b
Revises: 
Create Date: 2025-01-11 11:23:08.189325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9c5dbcd347b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribusi')
    op.drop_table('penerima')
    op.drop_table('daur_ulang')
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_donasi', sa.DateTime(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'penjual'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('admin', 'penjual'),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.drop_column('tanggal_donasi')

    op.create_table('daur_ulang',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama_donatur', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nomor_telp', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nama_tempat', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('jenis_makanan', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('jumlah_porsi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tanggal_kedaluwarsa', sa.DATE(), nullable=False),
    sa.Column('lokasi_donatur', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('deskripsi_tambahan', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('penerima',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama_penerima', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nomor_telepon', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('alamat_penerima', mysql.TEXT(), nullable=False),
    sa.Column('jenis_makanan_dibutuhkan', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('jumlah_porsi_dibutuhkan', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('jenis_penerima', mysql.ENUM('Perorangan', 'Yayasan', 'Lainnya'), nullable=False),
    sa.Column('keterangan_penerima', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('distribusi',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_donasi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_penerima', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_daur_ulang', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tanggal_distribusi', sa.DATE(), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'selesai'), server_default=sa.text("'pending'"), nullable=True),
    sa.ForeignKeyConstraint(['id_daur_ulang'], ['daur_ulang.id'], name='distribusi_ibfk_3'),
    sa.ForeignKeyConstraint(['id_donasi'], ['donasi.id'], name='distribusi_ibfk_1'),
    sa.ForeignKeyConstraint(['id_penerima'], ['penerima.id'], name='distribusi_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
